name: Main Commit Checks
on: [push]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                # The node version, you can put one or many versions in here to test with
                node: [15.6.0]
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
