name: Main Commit Checks
on: [push]

jobs:
    build:
        runs-on: macos-latest

        strategy:
            matrix:
                # The node version, you can put one or many versions in here to test with
                node: [15.6.0]
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            # This should be caching node modules, hashing the cache key with the yarn lock code and busting that when yarn lock changes
            - name: cache modules
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - run: sudo npm install
            
            - run: npm start
            
